export default function TermsPage() {
    return (
        <div className="min-h-screen pt-24 pb-16 grid-pattern">
            <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
                <h1 className="text-4xl font-bold font-display mb-2">Terms of Service</h1>
                <p className="text-gorbe-white/60 mb-8">Last updated: {new Date().toLocaleDateString()}</p>

                <div className="glass rounded-2xl p-8 space-y-6 text-gorbe-white/80">
                    <section>
                        <h2 className="text-xl font-semibold text-gorbe-lime mb-3">Acceptance of Terms</h2>
                        <p>
                            By using this website and interacting with Gorbe, you agree to these terms.
                            This is an experimental, entertainment-focused project.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-gorbe-lime mb-3">Risk Disclaimer</h2>
                        <p className="mb-2">
                            <strong className="text-gorbe-lime">IMPORTANT:</strong> Trading cryptocurrencies involves significant risk.
                        </p>
                        <ul className="list-disc list-inside space-y-1 text-gorbe-white/70">
                            <li>You may lose all your funds</li>
                            <li>This is NOT financial advice</li>
                            <li>Do your own research (DYOR)</li>
                            <li>Only invest what you can afford to lose</li>
                            <li>Past performance does not guarantee future results</li>
                        </ul>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-gorbe-lime mb-3">AI Disclaimer</h2>
                        <p>
                            Gorbe is an AI character for entertainment purposes only. His responses are:
                        </p>
                        <ul className="list-disc list-inside mt-2 space-y-1 text-gorbe-white/70">
                            <li>Generated by AI and may be inaccurate</li>
                            <li>Not financial, legal, or professional advice</li>
                            <li>Purely for entertainment and engagement</li>
                        </ul>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-gorbe-lime mb-3">No Guarantees</h2>
                        <p>
                            We make no guarantees about:
                        </p>
                        <ul className="list-disc list-inside mt-2 space-y-1 text-gorbe-white/70">
                            <li>Token value or price performance</li>
                            <li>Future development or features</li>
                            <li>Uptime or availability of services</li>
                            <li>Gorbe ever actually streaming (let's be real)</li>
                        </ul>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-gorbe-lime mb-3">Limitation of Liability</h2>
                        <p>
                            We are not liable for any losses incurred through use of this service,
                            including but not limited to: trading losses, missed opportunities,
                            technical failures, or disappointment that Gorbe still hasn't streamed.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-gorbe-lime mb-3">User Conduct</h2>
                        <p>
                            When chatting with Gorbe, please:
                        </p>
                        <ul className="list-disc list-inside mt-2 space-y-1 text-gorbe-white/70">
                            <li>Be respectful (Gorbe has feelings... kinda)</li>
                            <li>Don't try to make the AI do bad things</li>
                            <li>Don't spam or abuse the service</li>
                            <li>Have fun!</li>
                        </ul>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-gorbe-lime mb-3">Changes to Terms</h2>
                        <p>
                            We may update these terms at any time. Continued use of the service
                            constitutes acceptance of any changes.
                        </p>
                    </section>
                </div>
            </div>
        </div>
    );
}
